import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb1c4",
        "primary-container": "#34a547",
        "secondary-container": "#41474f",
        "on-primary-container": "#00320b",
        "outline-variant": "#3e4a3d",
        "tertiary-container": "#e9638e",
        "primary-fixed-dim": "#6fdd78",
        "tertiary-fixed": "#ffd9e1",
        "on-primary-fixed-variant": "#005319",
        "primary": "#6fdd78",
        "surface-container-lowest": "#0c0e12",
        "surface-bright": "#37393e",
        "inverse-surface": "#e2e2e8",
        "secondary": "#c1c7d0",
        "error": "#ffb4ab",
        "on-secondary-container": "#b0b5be",
        "inverse-primary": "#006e23",
        "surface-dim": "#111318",
        "on-tertiary-fixed": "#3f001a",
        "primary-fixed": "#8bfb91",
        "on-primary": "#00390e",
        "outline": "#889484",
        "background": "#111318",
        "on-error": "#690005",
        "on-secondary": "#2b3138",
        "on-tertiary-container": "#590028",
        "surface": "#111318",
        "on-tertiary": "#65002e",
        "on-secondary-fixed": "#161c23",
        "on-surface-variant": "#becab9",
        "on-error-container": "#ffdad6",
        "surface-tint": "#6fdd78",
        "on-tertiary-fixed-variant": "#891544",
        "secondary-fixed-dim": "#c1c7d0",
        "surface-container-highest": "#333539",
        "surface-container-low": "#1a1c20",
        "tertiary": "#ffb1c4",
        "on-background": "#e2e2e8",
        "on-surface": "#e2e2e8",
        "surface-variant": "#333539",
        "surface-container-high": "#282a2e",
        "inverse-on-surface": "#2f3035",
        "surface-container": "#1e2024",
        "error-container": "#93000a",
        "secondary-fixed": "#dde3ec",
        "on-secondary-fixed-variant": "#41474f",
        "on-primary-fixed": "#002106",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-margin": "24px",
        "sidebar-width": "260px",
        "gutter": "16px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "display-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "code-sm": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "code-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};

export default config;
